version: '3.9'
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - redis
    environment:
      - JWT_SECRET=randomstringusedtohashthejwtsoitdoesnotgetspoofedbypeople,replacethisstringassoonasyouhavetimeorifyouwanttousethisexperimentinproductionenvironment.
      - NODE_ENV=production
      - PASSWORD_ALGORITHM=argon2
      - PASSWORD_PEEPER=randomstringforsha512hash.wedonotwantanyonetoknowthis.youareseeingthisasthisisopensource.ifyouwanttousethisinproductionenvironment,donotusethis.
      - PORT=8080
      - SESSION_SECRET=randomstringthatisusedtodeclaresessionsecrettocreatesignedsessiontokens.pleasereplacethisvalueinproductionifyouwanttousethisinyourcompanyorsomething.
    command: yarn start

  redis:
    image: redis:6.2.5
    restart: always
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:
